services:
  api:
    image: python:3.12-slim
    working_dir: /app
    command: bash -lc "pip install -r backend/requirements.txt && uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
  web:
    image: node:22-alpine
    working_dir: /app/frontend
    command: sh -lc "npm i && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_URL=http://localhost:8001
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
