services:
  api:
    image: python:3.12-slim
    working_dir: /app
    # Enable auto-reload for backend code changes (dev only)
    command: bash -lc "pip install -r backend/requirements.txt && uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
  web:
    image: node:22-alpine
    working_dir: /app/frontend
    # Use polling so file changes on Windows/host volumes trigger Vite HMR
    command: sh -lc "npm i && CHOKIDAR_USEPOLLING=1 npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_URL=http://localhost:8001
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
